server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:sqlserver://DESKTOP-I1SMM2J\SQL;databaseName=ecommerce;trustServerCertificate=true
    username: ecom
    password: Ecom@12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show_sql: true
    hibernate:
      ddl-auto: none

  cloud:
      compatibility-verifier:
        enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
